memory_limit=512M
max_execution_time=0
date.timezone=UTC
phar.readonly=0
display_errors=On
log_errors=On
sys_temp_dir=/data/user/0/com.xtrmstudios.pocketminerunner/files/tmp
curl.cainfo=/data/user/0/com.xtrmstudios.pocketminerunner/files/pocketmine/config/cacert.pem
openssl.cafile=/data/user/0/com.xtrmstudios.pocketminerunner/files/pocketmine/config/cacert.pem
